### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Keksinautin** [Jackong/generator-cordova-react#1]
Hellow! 

After `yo cordova-react` a current folder contains the `package.json` file. It has a `generator cordova react` value in the `name` field. 
As a result `npm install` fails with `Invalid name: "generator cordova react"` message.
If I change `generator cordova react` to `generator-cordova-react` everything works fine.
I have no idea why it works this way. I see that the `name` field in the repository has a correct value. I tried installation from npm package (v.1.0.0) and from GitHub (v.1.1.1) and the results are the same.

My environment:
Ubuntu 14.04.3 LTS
node v4.2.1
npm  v2.14.7

**Comment by Jackong** [comment]
It is a bug for folder name with `-`. I have fixed it and publish `1.1.2`.

**Comment by Keksinautin** [comment]
Thank you very much.
